export const artPieces = [
  {
    id: 1,
    title: 'Art Piece 1',
    description: 'Art Piece 1 description',
    price: 100,
    imageUrl: 'https://example.com/image1.jpg',
    artistId: 1,
  },
  {
    id: 2,
    title: 'Art Piece 2',
    description: 'Art Piece 2 description',
    price: 200,
    imageUrl: 'https://example.com/image2.jpg',
    artistId: 1,
  },
  {
    id: 3,
    title: 'Art Piece 3',
    description: 'Art Piece 3 description',
    price: 300,
    imageUrl: 'https://example.com/image3.jpg',
    artistId: 1,
  },
  {
    id: 4,
    title: 'Art Piece 4',
    description: 'Art Piece 4 description',
    price: 400,
    imageUrl: 'https://example.com/image4.jpg',
    artistId: 2,
  },
  {
    id: 5,
    title: 'Art Piece 5',
    description: 'Art Piece 5 description',
    price: 500,
    imageUrl: 'https://example.com/image5.jpg',
    artistId: 2,
  },
  {
    id: 6,
    title: 'Art Piece 6',
    description: 'Art Piece 6 description',
    price: 600,
    imageUrl: 'https://example.com/image6.jpg',
    artistId: 2,
  },
];